name: Build one keyboard
on:
  workflow_dispatch:
    inputs:
      keyboard:
        description: "Which keyboard to build"
        required: true
        default: both
        type: choice
        options:
          - corne # SuperMini nRF52840 + Mifuny Corne v3 Choc v1
          - splitkb_aurora_corne # splitkb.com Aurora Corne
          - splitkb_aurora_corne_dongle # splitkb.com Aurora Corne + Halcyon Dongle
          - both

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: >-
        ${{ inputs.keyboard == 'corne' && 'build/corne.yaml'
         || inputs.keyboard == 'splitkb_aurora_corne' && 'build/splitkb_aurora_corne.yaml'
         || inputs.keyboard == 'splitkb_aurora_corne_dongle' && 'build/splitkb_aurora_corne_dongle.yaml'
         || 'build.yaml' }}
